# Generated by Django 4.1.13 on 2025-03-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210509_1408'),
    ]

    operations = [
    ]
